alias get-idf='. "$IDF_PATH/export.sh"'
alias ys='yosys'
alias ivlog='iverilog -o sim'
alias vvp-run='vvp sim'
alias gtkw='gtkwave dump.vcd'
alias eda='cd ~/Projects/EDA'
alias dft='cd ~/Projects/DFT'
alias openroad='podman run --rm -it -v $(pwd):/work -w /work ghcr.io/efabless/openlane2:2.3.9 openroad'
alias openlane='podman run --rm -it -v $(pwd):/work -w /work ghcr.io/efabless/openlane2:2.3.9 openlane'
alias openroad-gui='podman run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/work -w /work ghcr.io/efabless/openlane2:2.3.9 openroad -gui'
alias or-shell='podman run --rm -it -v $(pwd):/work -w /work ghcr.io/efabless/openlane2:2.3.9 bash'
alias avr-compile='avr-gcc -mmcu=atmega328p -DF_CPU=16000000UL -Os'
alias avr-hex='avr-objcopy -O ihex -R .eeprom'
alias avr-flash='avrdude -c arduino -p m328p -P /dev/ttyUSB0 -b 115200 -U flash:w:'
alias avr-size='avr-size --format=avr --mcu=atmega328p'
alias idf-build='idf.py build'
alias idf-flash='idf.py -p /dev/ttyUSB0 flash'
alias idf-monitor='idf.py -p /dev/ttyUSB0 monitor'
alias idf-all='idf.py -p /dev/ttyUSB0 flash monitor'
alias idf-new='idf.py create-project'
alias idf-clean='idf.py fullclean'
alias esp='cd ~/Projects/Embedded/esp32-idf'
alias uart='minicom -D /dev/ttyUSB0 -b 115200'
alias uart0='minicom -D /dev/ttyUSB0 -b 9600'
alias uart-list='ls /dev/tty{USB,ACM}* 2>/dev/null'
alias py='/usr/bin/python3'
alias pip3='/usr/bin/pip3'
alias jup='jupyter lab'
alias streamlit-run='streamlit run'
alias venv-new='python3 -m venv .venv && source .venv/bin/activate'
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'
alias glog='git log --oneline --graph --all'
alias gday='git add . && git commit -m "Daily progress update" && git push'
alias proj='cd ~/Projects'
alias emb='cd ~/Projects/Embedded'
alias cap='cd ~/Projects/Capstone/esp32-rpi-dashboard'
alias log='cd ~/Projects/march-learning-log && nano march_log.md'
alias update='sudo rpm-ostree upgrade'
alias ports='ls /dev/tty{USB,ACM}* 2>/dev/null || echo "No serial devices found"'
alias myip='hostname -I'
alias aliases='cat ~/.bashrc | grep "^alias" | sed "s/alias //" | sort'
alias bye='systemctl poweroff'
alias restart='systemctl reboot'
alias supernova='systemctl reboot'
alias c='clear'
alias aliasesupdate='cat ~/.bashrc | grep ^alias > ~/Desktop/gitPractice/aliases.conf'
